### ISSUE TITLE
Bad days

### ISSUE THREAD

**Issue by peio72** [bradberger/angular-material-calendar#18]
I noticed there is an issue with day of the calendarbfir October and other months near the end.
There are two "25" days. You can see it on the demo page too.

**Comment by bradberger** [comment]
Ouch, thanks for pointing it out. Seems like it's on every day. Must have happened during the latest update. Will check it as soon as possible.

**Comment by bradberger** [comment]
Something definitely is not working right, now noticing that several months are not recognizing the out of month days properly either.

**Comment by bradberger** [comment]
Turns out it was due to improper use of one-time bindings, so this should be fixed in b71129541a2df49a14fda6702b935487dd7501a8

**Comment by peio72** [comment]
Thanx. I still can't update with latest in my app for the moment because it breaks my ajax json request and still column resizing issue. Is there a way to disable the tooltip too ?

P.

**Comment by bradberger** [comment]
No the tooltip can't be disabled, but I can definitely [add that as an option](https://github.com/bradberger/angular-material-calendar/issues/19). Theoretically you could just load a custom template for now to do that without the tooltips.
